import { RESTRICTIONS } from './constants';
import type { Exercise, RestrictionSwaps } from './types';

const image = (slug: string) => `/exercises/${slug}.jpg`;
const youtube = (id: string) => `https://www.youtube.com/embed/${id}`;

/** Every restriction keeps the exercise unless an override names a safer variant. */
const swaps = (name: string, overrides: Partial<RestrictionSwaps> = {}): RestrictionSwaps =>
  Object.fromEntries(RESTRICTIONS.map((r) => [r, overrides[r] ?? name])) as RestrictionSwaps;

/**
 * Order matters: the generator takes the first match in several places,
 * so bodyweight basics stay at the top.
 */
export const EXERCISES: Exercise[] = [
  {
    id: 16,
    name: 'Bodyweight Glute Bridge',
    pattern: 'Hinge',
    equipmentNeeded: 'Bodyweight',
    level: 'Beginner',
    regression: 'Glute Bridge Isometric',
    progression: 'Single-leg Glute Bridge',
    restrictionSwaps: swaps('Bodyweight Glute Bridge', { 'Sin-Flexion-Profunda': 'Glute Bridge rango corto' }),
    videoUrl: youtube('4XJCngiQp_8'),
    imageUrl: image('glute-bridge'),
  },
  {
    id: 17,
    name: 'Prone Y-T-W Raises',
    pattern: 'Pull',
    equipmentNeeded: 'Bodyweight',
    level: 'Beginner',
    regression: 'Prone Cobra',
    progression: 'T-Raises sostenido',
    restrictionSwaps: swaps('Prone Y-T-W Raises'),
    videoUrl: youtube('-ZX1QMTdAC4'),
    imageUrl: image('prone-raises'),
  },
  {
    id: 18,
    name: 'Air Squat',
    pattern: 'Squat',
    equipmentNeeded: 'Bodyweight',
    level: 'Beginner',
    regression: 'Box Squat asistido',
    progression: 'Jump Squat',
    restrictionSwaps: swaps('Air Squat', { 'Sin-Flexion-Profunda': 'Box Squat parcial' }),
    videoUrl: youtube('L219ltL15zk'),
    imageUrl: image('air-squat'),
  },
  {
    id: 1,
    name: 'Goblet Squat',
    pattern: 'Squat',
    equipmentNeeded: 'Kettlebell',
    level: 'Intermediate',
    regression: 'Air Squat',
    progression: 'Double KB Front Squat',
    restrictionSwaps: swaps('Goblet Squat', { 'Sin-Flexion-Profunda': 'Box Squat parcial' }),
    videoUrl: youtube('MhllRFE_KzQ'),
    imageUrl: image('functional-training'),
  },
  {
    id: 2,
    name: 'Pull-ups',
    pattern: 'Pull',
    equipmentNeeded: 'Pull-up Bar',
    level: 'Advanced',
    regression: 'Ring Rows',
    progression: 'Weighted Pull-ups',
    restrictionSwaps: swaps('Pull-ups', { 'Sin-Empuje-Vertical': 'Ring Rows' }),
    videoUrl: youtube('eGo4IYtl4hE'),
    imageUrl: image('pull-ups'),
  },
  {
    id: 3,
    name: 'Push-ups',
    pattern: 'Push',
    equipmentNeeded: 'Bodyweight',
    level: 'Intermediate',
    regression: 'Knee Push-ups',
    progression: 'Clapping Push-ups',
    restrictionSwaps: swaps('Push-ups'),
    videoUrl: youtube('IODxDxX7oi4'),
    imageUrl: image('push-ups'),
  },
  {
    id: 4,
    name: 'Kettlebell Swing',
    pattern: 'Hinge',
    equipmentNeeded: 'Kettlebell',
    level: 'Intermediate',
    regression: 'Kettlebell Deadlift',
    progression: 'Single-arm KB Swing',
    restrictionSwaps: swaps('Kettlebell Swing'),
    videoUrl: youtube('YSxHifyI6s8'),
    imageUrl: image('kettlebell-swing'),
  },
  {
    id: 5,
    name: 'Burpees',
    pattern: 'Metabolic',
    equipmentNeeded: 'Bodyweight',
    level: 'Intermediate',
    regression: 'Sprawls (No push-up)',
    progression: 'Burpee Box Jump',
    restrictionSwaps: swaps('Burpees', {
      'Sin-Impacto': 'Burpee Caminado (Step-back)',
      'Sin-Flexion-Profunda': 'Sprawls a banco',
    }),
    videoUrl: youtube('TU8QYVW0gDU'),
    imageUrl: image('strength-floor'),
  },
  {
    id: 6,
    name: 'Dumbbell Overhead Press',
    pattern: 'Push',
    equipmentNeeded: 'Dumbbells',
    level: 'Intermediate',
    regression: 'Seated DB Press',
    progression: 'Barbell Push Press',
    restrictionSwaps: swaps('Dumbbell Overhead Press', { 'Sin-Empuje-Vertical': 'DB Floor Press' }),
    videoUrl: youtube('QAQ64hK4Xxs'),
    imageUrl: image('functional-training'),
  },
  {
    id: 7,
    name: 'Box Jumps',
    pattern: 'Metabolic',
    equipmentNeeded: 'Plyo Box',
    level: 'Intermediate',
    regression: 'Box Step-ups',
    progression: 'High Box Jumps',
    restrictionSwaps: swaps('Box Jumps', {
      'Sin-Impacto': 'Box Step-ups',
      'Sin-Flexion-Profunda': 'Box Step-ups bajos',
    }),
    videoUrl: youtube('52r_Ul5k03g'),
    imageUrl: image('functional-training'),
  },
  {
    id: 8,
    name: 'Deadbug',
    pattern: 'Core',
    equipmentNeeded: 'Bodyweight',
    level: 'Beginner',
    regression: 'Tabletop Hold',
    progression: 'Weighted Deadbug',
    restrictionSwaps: swaps('Deadbug'),
    videoUrl: youtube('4XJCngiQp_8'),
    imageUrl: image('core'),
  },
  {
    id: 9,
    name: 'Walking Lunges',
    pattern: 'Squat',
    equipmentNeeded: 'Bodyweight',
    level: 'Intermediate',
    regression: 'Reverse Lunges',
    progression: 'Weighted Walking Lunges',
    restrictionSwaps: swaps('Walking Lunges', { 'Sin-Flexion-Profunda': 'Reverse Lunges superficiales' }),
    videoUrl: youtube('L8fvypPrzzs'),
    imageUrl: image('lunges'),
  },
  {
    id: 10,
    name: 'Thrusters',
    pattern: 'Metabolic',
    equipmentNeeded: 'Dumbbells',
    level: 'Advanced',
    regression: 'Front Squat',
    progression: 'Heavy Barbell Thrusters',
    restrictionSwaps: swaps('Thrusters', {
      'Sin-Flexion-Profunda': 'Push Press',
      'Sin-Empuje-Vertical': 'Front Squat',
    }),
    videoUrl: youtube('L219ltL15zk'),
    imageUrl: image('functional-training'),
  },
  {
    id: 11,
    name: "World's Greatest Stretch",
    pattern: 'Mobility',
    equipmentNeeded: 'Bodyweight',
    level: 'Beginner',
    regression: 'Kneeling Lunge Stretch',
    progression: "World's Greatest Stretch with rotation",
    restrictionSwaps: swaps("World's Greatest Stretch", { 'Sin-Flexion-Profunda': 'Standing Quad Stretch' }),
    videoUrl: youtube('-ZX1QMTdAC4'),
    imageUrl: image('lunges'),
  },
  {
    id: 12,
    name: 'Sandbag Clean',
    pattern: 'Hinge',
    equipmentNeeded: 'Sandbag',
    level: 'Advanced',
    regression: 'Sandbag Deadlift',
    progression: 'Sandbag Clean & Press',
    restrictionSwaps: swaps('Sandbag Clean', { 'Sin-Flexion-Profunda': 'Sandbag Deadlift' }),
    videoUrl: youtube('MhllRFE_KzQ'),
    imageUrl: image('strength-floor'),
  },
  {
    id: 13,
    name: 'Medicine Ball Slam',
    pattern: 'Metabolic',
    equipmentNeeded: 'Medicine Ball',
    level: 'Intermediate',
    regression: 'Squat to overhead reach',
    progression: 'Jumping Medball Slam',
    restrictionSwaps: swaps('Medicine Ball Slam', {
      'Sin-Flexion-Profunda': 'Medball Slam superficial',
      'Sin-Empuje-Vertical': 'Medicine Ball Rotational Slam',
    }),
    videoUrl: youtube('YSxHifyI6s8'),
    imageUrl: image('functional-training'),
  },
  {
    id: 14,
    name: 'Double Under (Jump Rope)',
    pattern: 'Metabolic',
    equipmentNeeded: 'Jump Rope',
    level: 'Advanced',
    regression: 'Single Unders',
    progression: 'Triple Unders',
    restrictionSwaps: {
      'Sin-Impacto': 'Fast High Knees (No jump)',
      'Sin-Flexion-Profunda': 'Double Under',
      'Sin-Empuje-Vertical': 'Double Under',
    },
    videoUrl: youtube('eGo4IYtl4hE'),
    imageUrl: image('functional-training'),
  },
  {
    id: 15,
    name: 'Barbell Deadlift',
    pattern: 'Hinge',
    equipmentNeeded: 'Barbell',
    level: 'Intermediate',
    regression: 'Kettlebell Deadlift',
    progression: 'Deficit Deadlift',
    restrictionSwaps: swaps('Barbell Deadlift', { 'Sin-Flexion-Profunda': 'Block Deadlift (rango corto)' }),
    videoUrl: youtube('QAQ64hK4Xxs'),
    imageUrl: image('strength-floor'),
  },
];
